---
# tasks file for jpnewman.common

- name: Load OS Family variables
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Load OS Codename variables, if exists
  include_vars: "{{ ansible_lsb.codename | lower }}.yml"
  ignore_errors: True
  changed_when: False

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 600
  changed_when: False

- name: Set fact apt_packages.
  set_fact:
    apt_packages: "{{ __apt_packages | list }}"
  when: apt_packages is not defined

- name: Install packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    '{{ apt_packages }}'

- name: Check alternative editor
  command: >
    ls -lha /etc/alternatives/editor
  register: alt_editor
  check_mode: no
  changed_when: False

- name: Update alternative editor
  command: >
    update-alternatives --set editor {{ alternative_editor }}
  when: alternative_editor not in alt_editor.stdout

- name: Configure skel bash aliases
  lineinfile:
    dest: /etc/skel/.bash_aliases
    line: "{{ item }}"
    state: present
    create: yes
  with_items:
    - 'alias ll="ls -l"'
    - 'alias la="ls -lha"'

- name: Update limits
  lineinfile:
    dest: "{{ limits_conf_file }}"
    regexp: "^{{ item.domain | regex_escape() }}\\s+{{ item.type | regex_escape() }}\\s+{{ item.item | regex_escape() }}\\s+{{ item.value | regex_escape() }}$"
    line: "{{ item.domain.ljust(16) }} {{ item.type.ljust(7) }} {{ item.item.ljust(15) }} {{ item.value | trim}}"
    insertbefore: "^# End of file"
  with_items: "{{ limits }}"

- name: Configure pam_limits.so
  lineinfile:
    dest: "{{ item }}"
    regexp: '^\s*#?\s*session\s+required\s+pam_limits.so'
    insertafter: EOF
    line: 'session    required    pam_limits.so'
  when: limits | length > 0
  with_items:
    - /etc/pam.d/su
    - /etc/pam.d/common-session
    - /etc/pam.d/common-session-noninteractive
    - /etc/pam.d/sudo
